### ISSUE TITLE
CastModifier and Bartender2 Issue

### ISSUE THREAD

**Issue by Grumblebeard** [DennisWG/CastModifier#14] opened 2017-03-07 06:44 UTC
If both CastModifier and Bartender are activated, the functionality of the HunterBars ceases to function. This function is designed to swap a bar (default, the main bar) with another bar upon which melee range spells/items/macros can be used. It does this by checking if the target is auto shot range and interact range 2, but not in melee (to establish the deadzone), and then when the target moves into melee it swaps to the other specified bar. To reiterate, CastModifier in some way prevents this script from functioning, and the bar swapping breaks.

**Comment by DennisWG** [comment] 2017-03-13 09:39
I wasn't able to find any incompatibilities.

The HunterBars Addon requires you to have the Auto Shot ability somewhere on your Action Bars. This can not be a Macro, it has to be the ability. Are you certain that you have it on any of your Action Bars?

Also, although this has nothing to do with the issue, HunterBars doesn't check for the dead zone. It checks whether you're in trading distance which is 11.11 yards.

**Comment by Grumblebeard** [comment] 2017-03-13 21:01
I do have the regular auto shot ability on my bars, I tested for that myself. To the best of my knowledge B2 has to use the limited check interact distance functions to basically guestimate the deadzone, and given that on my current server the trade distance (which is supposed to be 11.11 yards) is closer to 9 yards, that doesn't cause an issue.

**Comment by DennisWG** [comment] 2017-03-14 11:32
Since I fail to reproduce this, let's try these things:

- Please upload your Bartender2 and HunterBars and send them to me. Maybe I'm using a different version
- Tell me what locale your client is using (I officially only support enUS right now)
- Make sure you have downloaded the latest version of CastModifier
- Have you tried disabling all other Addons besides CastModifier, Bartender 2 and HunterBars? If not, please do so and try again
- How is HunterBars configured?
- How are your Action Bars configured?

The more in-depth you can go the easier it'll be for me to find this bug.

**Comment by DennisWG** [comment] 2017-03-31 05:41
I'll close this since no more information was provided. Feel free to reopen it once my previous questions are answered.

**Closed by DennisWG** 2017-03-31 05:41 UTC
