### ISSUE TITLE
Macros fail if not all conditions met

### ISSUE THREAD

**Issue by Lorilay2** [DennisWG/CastModifier#6] opened 2016-12-21 06:54 UTC
For example, if I have a macro that casts a spell and announces it to the raid, if I am not in a raid group the macro will do nothing. With this addon disabled, it normally would cast the spell anyways.

For example:
```
/cast Healing Touch
/ra Casting Healing Touch!
```

This macro will work in a raid group, but do nothing if you are not in one. This is also the case for macros that combine multiple abilities, such as the following, which will do nothing at all with this addon enabled (but normally attempts to cast all three abilities, and only casts the first one listed that is available):

```
/cast Counterattack
/cast Mongoose Bite
/cast Raptor Strike
```

**Comment by DennisWG** [comment] 2016-12-21 17:31
I'm unable to reproduce these errors. 
Can you try it without any other Addons enabled? If it works, turn them on again one by one until these macros no longer function. I assume there's some kind of conflict. If you can find out what Addon is causing the issue, I can work on a compatibility fix.

**Comment by Lorilay2** [comment] 2016-12-21 21:11
After doing that, it looks like a conflict with SuperMacro.

**Comment by DennisWG** [comment] 2016-12-23 15:56
Should be fixed now!

**Closed** 2016-12-23 15:56 UTC
